import React from 'react';
import type { Insight } from '../../types/dashboard';
import { EmptyState } from '../common/EmptyState';
import { InsightCard } from './InsightCard';

export function InsightsPanel({ insights }: {insights: Insight[];}) {
  return (
    <section aria-labelledby="insights-heading" className="flex flex-col rounded-xl border border-line bg-surface p-5 shadow-card">
      <h2 id="insights-heading" className="text-base font-semibold text-fg">
        Executive insights
      </h2>
      <p className="mt-0.5 text-xs text-muted">Generated by the analytics service for this selection</p>
      <div className="mt-4 flex-1">
        {insights.length ?
        <ul className="divide-y divide-line">
            {insights.map((insight) =>
          <InsightCard key={insight.id} insight={insight} />
          )}
          </ul> :

        <EmptyState compact title="No insights returned for this selection." />
        }
      </div>
    </section>);

}